/*
 * Native Penpot build specification for SolvAI Figure 1.
 *
 * Execute this file through the official Penpot MCP `execute_code` tool after
 * loading the SVG source assets into `storage.assets`.  The output remains a
 * fully editable Penpot document: typography, rules, arrows, taxonomy nodes,
 * labels, and panel geometry are native Penpot objects; chemistry and physical
 * scenes are imported as editable SVG groups generated by scientific tools.
 */

const P = {
  orange: "#D97718",
  orange2: "#E9A14D",
  orangePale: "#FFF5E8",
  blue: "#2477B3",
  blue2: "#62A7D5",
  bluePale: "#ECF5FB",
  teal: "#0B8978",
  teal2: "#50AD9F",
  tealPale: "#E9F7F4",
  charcoal: "#26323B",
  muted: "#66747E",
  light: "#94A2AB",
  rule: "#D6DFE4",
  paper: "#FFFFFF",
  wash: "#F7F9FA",
  magenta: "#B53D76",
  magentaPale: "#FBEFF5",
};

const FONT = "Inter";
const W = 1800;
const H = 1120;

function addText(parent, value, x, y, size, color = P.charcoal, weight = 400, name = value) {
  const t = penpot.createText(value);
  t.name = name;
  t.x = x;
  t.y = y;
  t.fontFamily = FONT;
  t.fontSize = String(size);
  t.fontWeight = String(weight);
  t.lineHeight = "1.12";
  t.fills = [{ fillColor: color, fillOpacity: 1 }];
  parent.appendChild(t);
  return t;
}

function rect(parent, x, y, w, h, fill, name, radius = 0, stroke = null, strokeWidth = 1) {
  const s = penpot.createRectangle();
  s.name = name;
  s.x = x;
  s.y = y;
  s.resize(w, h);
  s.fills = fill ? [{ fillColor: fill, fillOpacity: 1 }] : [];
  s.borderRadius = radius;
  s.strokes = stroke
    ? [{ strokeColor: stroke, strokeOpacity: 1, strokeWidth }]
    : [];
  parent.appendChild(s);
  return s;
}

function ellipse(parent, x, y, w, h, fill, name, stroke = null, strokeWidth = 1) {
  const s = penpot.createEllipse();
  s.name = name;
  s.x = x;
  s.y = y;
  s.resize(w, h);
  s.fills = fill ? [{ fillColor: fill, fillOpacity: 1 }] : [];
  s.strokes = stroke
    ? [{ strokeColor: stroke, strokeOpacity: 1, strokeWidth }]
    : [];
  parent.appendChild(s);
  return s;
}

function rule(parent, x, y, w, color = P.rule, thickness = 2, name = "Rule") {
  return rect(parent, x, y, w, thickness, color, name);
}

function importAsset(parent, key, x, y, w, h, name) {
  if (!storage.assets || !storage.assets[key]) {
    throw new Error(`Missing Penpot asset: ${key}`);
  }
  const s = penpot.createShapeFromSvg(storage.assets[key]);
  if (!s) throw new Error(`Penpot could not parse SVG asset: ${key}`);
  s.name = name || key;
  s.x = x;
  s.y = y;
  s.resize(w, h);
  parent.appendChild(s);
  return s;
}

function arrow(parent, x1, y1, x2, y2, color, name = "Arrow", width = 3) {
  const dx = x2 - x1;
  const dy = y2 - y1;
  const len = Math.max(1, Math.sqrt(dx * dx + dy * dy));
  const angle = Math.atan2(dy, dx) * 180 / Math.PI;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${len}" height="18" viewBox="0 0 ${len} 18"><path d="M1 9 H${Math.max(4, len - 12)}" fill="none" stroke="${color}" stroke-width="${width}" stroke-linecap="round"/><path d="M${len - 13} 2 L${len - 1} 9 L${len - 13} 16 Z" fill="${color}"/></svg>`;
  const s = penpot.createShapeFromSvg(svg);
  s.name = name;
  s.x = x1;
  s.y = y1 - 9;
  s.rotate(angle);
  parent.appendChild(s);
  return s;
}

function splitFlow(parent, x, y, w, h, color, name = "Split flow") {
  const c = w / 2;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><path d="M${c} 1 V${h * 0.25} M${c} ${h * 0.25} L18 ${h - 10} M${c} ${h * 0.25} L${w - 18} ${h - 10}" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round"/><path d="M12 ${h - 14} L18 ${h} L27 ${h - 13} Z" fill="${color}"/><path d="M${w - 27} ${h - 13} L${w - 18} ${h} L${w - 12} ${h - 14} Z" fill="${color}"/></svg>`;
  const s = penpot.createShapeFromSvg(svg);
  s.name = name;
  s.x = x;
  s.y = y;
  parent.appendChild(s);
  return s;
}

function mergeFlow(parent, x, y, w, h, color, name = "Merge flow", branches = 2) {
  const c = w / 2;
  const starts = branches === 3 ? [20, c, w - 20] : [20, w - 20];
  const paths = starts.map((sx) => `M${sx} 1 L${c} ${h - 13}`).join(" ");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><path d="${paths}" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round"/><path d="M${c - 8} ${h - 15} L${c} ${h} L${c + 8} ${h - 15} Z" fill="${color}"/></svg>`;
  const s = penpot.createShapeFromSvg(svg);
  s.name = name;
  s.x = x;
  s.y = y;
  parent.appendChild(s);
  return s;
}

function panelLabel(parent, letter, title, subtitle, x, y, color) {
  addText(parent, letter, x, y - 4, 38, P.charcoal, 700, `Panel ${letter}`);
  addText(parent, title, x + 54, y, 28, color, 700, `${letter} title`);
  addText(parent, subtitle, x + 54, y + 44, 19, color, 600, `${letter} subtitle`);
}

function stageTag(parent, value, x, y, color, pale, width = 136) {
  rect(parent, x, y, width, 34, pale, `Tag ${value}`, 17);
  addText(parent, value, x + 16, y + 7, 16, color, 700, `Tag text ${value}`);
}

function numberedItem(parent, n, label, x, y, color, size = 18) {
  ellipse(parent, x, y + 1, 24, 24, color, `Prior ${n} node`);
  const nt = addText(parent, String(n), x + (n < 10 ? 7 : 4), y + 4, 13, P.paper, 700, `Prior ${n} number`);
  const tt = addText(parent, label, x + 36, y, size, P.charcoal, 400, `Prior ${n} ${label}`);
  return [nt, tt];
}

function responseFamily(parent, title, items, x, y, w, color = P.blue, lineGap = 37) {
  addText(parent, title.toUpperCase(), x, y, 18, color, 700, `${title} family`);
  rule(parent, x, y + 29, w, color, 2, `${title} family rule`);
  let cursor = y + 47;
  items.forEach((it) => {
    numberedItem(parent, it[0], it[1], x, cursor, color, 17);
    cursor += lineGap + (it[1].includes("\n") ? 18 : 0);
  });
}

function priorChip(parent, n, label, x, y, w, h = 40, fontSize = 15) {
  rect(parent, x, y, w, h, "#EAF4FA", `Prior ${n} coordinate`, 12, "#C3DDEC", 1);
  ellipse(parent, x + 9, y + (h - 24) / 2, 24, 24, P.blue, `Prior ${n} node`);
  addText(parent, String(n), x + (n < 10 ? 16 : 13), y + (h - 17) / 2, 13, P.paper, 700, `Prior ${n} number`);
  addText(parent, label, x + 43, y + 8, fontSize, P.charcoal, 400, `Prior ${n} ${label}`);
}

function drawResponseConstellation(board, x, y, width) {
  const connector = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="570" viewBox="0 0 ${width} 570"><path d="M325 105 C235 125 190 135 150 155 M325 105 C415 125 460 135 500 155 M325 105 C230 215 195 300 150 365 M325 105 C420 215 465 300 500 365" fill="none" stroke="#BDD8EA" stroke-width="2"/><circle cx="150" cy="155" r="5" fill="#2477B3"/><circle cx="500" cy="155" r="5" fill="#2477B3"/><circle cx="150" cy="365" r="5" fill="#2477B3"/><circle cx="500" cy="365" r="5" fill="#2477B3"/></svg>`;
  const links = penpot.createShapeFromSvg(connector);
  links.name = "Response taxonomy connectors";
  links.x = x;
  links.y = y;
  board.appendChild(links);

  ellipse(board, x + 275, y, 100, 100, P.bluePale, "15-coordinate hub", P.blue, 3);
  addText(board, "15", x + 307, y + 22, 40, P.blue, 700, "15 response coordinates");
  addText(board, "named scalars", x + 291, y + 70, 16, P.blue, 600);

  addText(board, "CALCULATED SOLVATION", x, y + 150, 18, P.blue, 700);
  rule(board, x, y + 180, 286, P.blue, 2, "Calculated family rule");
  priorChip(board, 1, "COSMOtherm water response", x, y + 194, 286, 40, 15);
  priorChip(board, 9, "SMD(water) response", x, y + 240, 286, 40, 15);

  addText(board, "POLARITY / H-BONDING", x + 340, y + 150, 18, P.blue, 700);
  rule(board, x + 340, y + 180, 310, P.blue, 2, "Abraham family rule");
  priorChip(board, 2, "Abraham E · excess molar\nrefraction", x + 340, y + 194, 150, 50, 15);
  priorChip(board, 3, "Abraham S · dipolarity /\npolarizability", x + 500, y + 194, 150, 50, 15);
  priorChip(board, 4, "Abraham A · H-bond acidity", x + 340, y + 250, 150, 44, 15);
  priorChip(board, 5, "Abraham B · H-bond basicity", x + 500, y + 250, 150, 44, 15);
  priorChip(board, 6, "Abraham L · hexadecane–air\npartition", x + 420, y + 300, 184, 50, 15);

  addText(board, "EXPLICIT / IMPLICIT WATER", x, y + 360, 18, P.blue, 700);
  rule(board, x, y + 390, 286, P.blue, 2, "Water family rule");
  priorChip(board, 7, "corrected OpenFF explicit-water\nresponse", x, y + 404, 286, 50, 15);
  priorChip(board, 8, "corrected GBn2 implicit-solvent\nresponse", x, y + 460, 286, 50, 15);

  addText(board, "CONFORMATIONAL RESPONSE", x + 340, y + 360, 18, P.blue, 700);
  rule(board, x + 340, y + 390, 310, P.blue, 2, "Conformer family rule");
  const conf = [
    [10, "gas conformer\ncorrection"],
    [11, "solution conformer\ncorrection"],
    [12, "hydration conformer\ncorrection"],
    [13, "conformer solvation-\nenergy spread"],
    [14, "mean conformer\nsolvent response"],
    [15, "conformer response\nspread"],
  ];
  conf.forEach((it, i) => priorChip(board, it[0], it[1], x + 340 + (i % 2) * 158, y + 404 + Math.floor(i / 2) * 56, 150, 50, 15));
}

function descriptorGlyph(parent, x, y, color = P.charcoal, accent = P.blue) {
  const positions = [0, 13, 26, 47, 60, 73, 94, 107, 120];
  positions.forEach((dx, i) => ellipse(parent, x + dx, y + (i % 3) * 7, i % 4 === 0 ? 7 : 5, i % 4 === 0 ? 7 : 5, i > 4 ? accent : color, `Descriptor bit ${i}`));
}

function forestGlyph(parent, x, y, color = P.teal, scale = 1) {
  for (let i = 0; i < 3; i++) {
    const bx = x + i * 44 * scale;
    rect(parent, bx + 18 * scale, y + 30 * scale, 3 * scale, 52 * scale, color, `Tree ${i + 1} trunk`);
    rule(parent, bx + 3 * scale, y + 32 * scale, 34 * scale, color, 3 * scale, `Tree ${i + 1} crown line`);
    ellipse(parent, bx, y + 25 * scale, 9 * scale, 9 * scale, color, `Tree ${i + 1} node a`);
    ellipse(parent, bx + 15 * scale, y + 10 * scale, 9 * scale, 9 * scale, color, `Tree ${i + 1} node b`);
    ellipse(parent, bx + 31 * scale, y + 25 * scale, 9 * scale, 9 * scale, color, `Tree ${i + 1} node c`);
    rule(parent, bx + 7 * scale, y + 28 * scale, 14 * scale, color, 2 * scale, `Tree ${i + 1} branch a`);
    rule(parent, bx + 20 * scale, y + 28 * scale, 14 * scale, color, 2 * scale, `Tree ${i + 1} branch b`);
  }
}

function sourceCaption(parent, title, detail, x, y, width = 230) {
  addText(parent, title, x, y, 20, P.charcoal, 600, `${title} title`);
  addText(parent, detail, x, y + 34, 17, P.muted, 400, `${title} detail`);
  rule(parent, x, y + 65, width, P.orange, 2, `${title} accent`);
}

function createBoardOnPage(pageName, boardName) {
  const page = penpot.currentFile.pages.find((p) => p.name === pageName);
  if (!page) throw new Error(`Page not found: ${pageName}`);
  return penpot.openPage(page).then(() => {
    for (const s of [...penpot.root.children]) s.remove();
    const board = penpot.createBoard();
    board.name = boardName;
    board.x = 0;
    board.y = 0;
    board.resize(W, H);
    board.fills = [{ fillColor: P.paper, fillOpacity: 1 }];
    board.clipContent = true;
    return board;
  });
}

function drawSourceQuartet(board, x, y, compact = false) {
  const cellW = compact ? 225 : 250;
  const gap = compact ? 25 : 30;
  const visualH = compact ? 125 : 155;
  sourceCaption(board, "Calculated solvation", "COSMOtherm · SMD(water)", x, y, cellW);
  importAsset(board, "cavity", x + 28, y + 83, cellW - 55, visualH, "Continuum cavity — RDKit geometry");
  importAsset(board, "molecule", x + 78, y + 127, cellW - 155, visualH - 78, "Molecule inside continuum cavity");

  sourceCaption(board, "Polarity / H-bonding", "Abraham E · S · A · B · L", x + cellW + gap, y, cellW);
  importAsset(board, "abraham", x + cellW + gap + 35, y + 84, cellW - 70, visualH - 5, "Abraham coordinate glyph");

  const y2 = y + (compact ? 270 : 310);
  sourceCaption(board, "Water response", "OpenFF explicit · GBn2 implicit", x, y2, cellW);
  importAsset(board, "waterShell", x + 18, y2 + 78, cellW - 36, visualH + 10, "Packmol solute–water configuration");

  sourceCaption(board, "Conformational response", "ConfSolv H₂O · six summaries", x + cellW + gap, y2, cellW);
  importAsset(board, "conformers", x + cellW + gap + 8, y2 + 88, cellW - 16, visualH - 5, "RDKit ETKDG/MMFF conformers");
}

function drawResponseAtlas(board, x, y, width, compact = false) {
  const col = width / 2 - 22;
  responseFamily(board, "Calculated solvation", [
    [1, "COSMOtherm water response"],
    [9, "SMD(water) response"],
  ], x, y, col, P.blue, 39);
  responseFamily(board, "Polarity / H-bonding", [
    [2, "Abraham E · excess molar\nrefraction"],
    [3, "Abraham S · dipolarity /\npolarizability"],
    [4, "Abraham A · H-bond acidity"],
    [5, "Abraham B · H-bond basicity"],
    [6, "Abraham L · hexadecane–air\npartition"],
  ], x + col + 44, y, col, P.blue, compact ? 31 : 37);
  const y2 = y + (compact ? 245 : 278);
  responseFamily(board, "Explicit / implicit water", [
    [7, "corrected OpenFF explicit-water\nresponse"],
    [8, "corrected GBn2 implicit-solvent\nresponse"],
  ], x, y2, col, P.blue, 39);
  responseFamily(board, "Conformational response", [
    [10, "gas conformer correction"],
    [11, "solution conformer correction"],
    [12, "hydration conformer correction"],
    [13, "conformer solvation-energy spread"],
    [14, "mean conformer solvent response"],
    [15, "conformer response spread"],
  ], x + col + 44, y2, col, P.blue, compact ? 30 : 34);
}

function drawEndpoint(board, x, y, width, compact = false) {
  const narrow = width < 620;
  rule(board, x, y, width, P.rule, 2, "Endpoint separator");
  stageTag(board, "STAGE 2", x + 4, y + 24, P.teal, P.tealPale, 112);
  addText(board, "experimentally supervised endpoint", x + 132, y + 31, 21, P.teal, 600);

  const yGlyph = y + 120;
  descriptorGlyph(board, x + 46, yGlyph + 12, P.charcoal, P.blue);
  addText(board, narrow ? "structure" : "STRUCTURE", x + 8, yGlyph + 66, 16, P.charcoal, 700);
  addText(board, narrow ? "2,265 features" : "2,265 features", x + 8, yGlyph + 93, 15, P.muted, 400);

  const rx = x + width * 0.40;
  for (let i = 0; i < 15; i++) {
    ellipse(board, rx + (i % 8) * 16, yGlyph + (i > 7 ? 25 : 8), 8, 8, i < 5 ? P.blue2 : P.blue, `Response coordinate ${i + 1}`);
  }
  addText(board, narrow ? "15 responses" : "RESPONSE", rx - 8, yGlyph + 66, 16, P.blue, 700);
  addText(board, narrow ? "predicted" : "15 coordinates", rx - 8, yGlyph + 93, 15, P.muted, 400);

  const ex = x + width * 0.76;
  rule(board, ex, yGlyph + 23, 100, P.teal, 2, "Experimental uncertainty line");
  ellipse(board, ex + 45, yGlyph + 12, 22, 22, P.teal, "Experimental value");
  addText(board, narrow ? "experimental ΔG" : "EXPERIMENT", ex - 20, yGlyph + 66, 16, P.teal, 700);
  addText(board, narrow ? "training labels" : "ΔGhyd labels", ex - 20, yGlyph + 93, 15, P.muted, 400);

  const targetX = x + width * 0.5;
  const targetY = y + (compact ? 280 : 315);
  mergeFlow(board, x + 80, yGlyph + 125, width - 160, 48, P.teal, "Three endpoint inputs merge", 3);
  forestGlyph(board, targetX - 55, targetY, P.teal, 0.9);
  addText(board, "ExtraTrees endpoint ensemble", targetX - 128, targetY + 86, 22, P.teal, 700);
  addText(board, "3 × 360 trees · frozen after evaluation", targetX - 137, targetY + 118, 16, P.muted, 400);
}

function drawDeployment(board, x, y, width, spacious = true) {
  const center = x + width / 2;
  addText(board, "NEW MOLECULE", center - 95, y, 18, P.muted, 700);
  addText(board, "CNC(C)=O", center - 77, y + 42, 27, P.charcoal, 500);
  importAsset(board, "molecule", center - 96, y + 88, 192, 126, "Deployment RDKit molecule");
  arrow(board, center, y + 238, center, y + 292, P.teal, "Molecule to feature branches", 4);

  const branchY = y + 350;
  descriptorGlyph(board, x + 30, branchY, P.charcoal, P.blue);
  addText(board, "structure", x + 45, branchY + 62, 18, P.charcoal, 600);
  addText(board, "2,265 features", x + 26, branchY + 91, 16, P.muted, 400);
  addText(board, "+", center - 10, branchY + 18, 33, P.muted, 600);
  for (let i = 0; i < 15; i++) ellipse(board, x + width - 170 + (i % 8) * 15, branchY + (i > 7 ? 24 : 7), 7, 7, i < 6 ? P.blue2 : P.blue, `Deployment response ${i + 1}`);
  addText(board, "frozen surrogates", x + width - 190, branchY + 62, 18, P.blue, 600);
  addText(board, "15 responses", x + width - 162, branchY + 91, 16, P.blue, 400);
  splitFlow(board, x + 58, y + 294, width - 116, 48, P.teal, "Structure and response branches");
  mergeFlow(board, x + 58, branchY + 126, width - 116, 65, P.teal, "Feature branches merge", 2);
  forestGlyph(board, center - 50, branchY + 205, P.teal, 0.8);
  addText(board, "SolvAI", center - 67, branchY + 292, 38, P.teal, 700);
  addText(board, "frozen endpoint ensemble", center - 111, branchY + 343, 16, P.muted, 400);
  arrow(board, center, branchY + 380, center, branchY + 438, P.teal, "SolvAI to output", 4);
  addText(board, "ΔG", center - 64, branchY + 465, 49, P.teal, 500, "Hydration free-energy symbol");
  addText(board, "hyd", center + 15, branchY + 494, 24, P.teal, 500, "Hydration free-energy subscript");
  addText(board, "kcal mol⁻¹", center - 48, branchY + 528, 17, P.muted, 400);
  addText(board, "SMILES only · no MD · no PIMD · no probe", center - 179, branchY + 568, 17, P.teal, 700);
}

async function buildMinimal() {
  const b = await createBoardOnPage("Variant A — minimal", "FIG1_A_MINIMAL");
  panelLabel(b, "a", "PHYSICAL RESPONSE", "generated once", 34, 24, P.orange);
  panelLabel(b, "b", "REUSABLE RESPONSE", "15 interpretable coordinates", 610, 24, P.blue);
  panelLabel(b, "c", "STRUCTURE-ONLY", "deployment", 1330, 24, P.teal);
  rule(b, 575, 24, 2, P.rule, 1030, "Panel divider AB");
  rule(b, 1295, 24, 2, P.rule, 1030, "Panel divider BC");

  drawSourceQuartet(b, 40, 125, true);
  stageTag(b, "STAGE 1", 42, 735, P.blue, P.bluePale, 112);
  addText(b, "learn structure → response", 174, 742, 20, P.blue, 600);
  importAsset(b, "molecule", 74, 810, 116, 76, "Stage 1 molecule");
  arrow(b, 213, 850, 285, 850, P.blue, "Structure to surrogates", 3);
  for (let i = 0; i < 6; i++) ellipse(b, 306 + (i % 3) * 37, 820 + Math.floor(i / 3) * 45, 25, 25, i < 2 ? P.blue : P.bluePale, `Frozen surrogate ${i + 1}`, P.blue);
  arrow(b, 430, 850, 535, 850, P.blue, "Surrogates to response", 3);
  addText(b, "learned once", 224, 913, 17, P.muted, 400);

  drawResponseAtlas(b, 618, 130, 640, true);
  drawEndpoint(b, 620, 690, 635, true);

  drawDeployment(b, 1320, 124, 438, true);
  rule(b, 1325, 1060, 428, P.magenta, 2, "PIMD8 comparator rule");
  addText(b, "ARROW/PIMD8 ≈ 0.205 kcal mol⁻¹", 1377, 1070, 17, P.magenta, 700);
  addText(b, "accuracy reference only · not a retained teacher", 1360, 1096, 14, P.muted, 400);
  return b.id;
}

async function buildMolecular() {
  const b = await createBoardOnPage("Variant B — molecular", "FIG1_B_MOLECULAR");
  rect(b, 0, 0, 690, H, P.orangePale, "Physical response wash");
  rect(b, 690, 0, 650, H, P.paper, "Response layer field");
  rect(b, 1340, 0, 460, H, P.tealPale, "Deployment wash");
  panelLabel(b, "a", "SOLVATION PHYSICS", "source calculations and response coordinates", 30, 22, P.orange);
  panelLabel(b, "b", "AMORTIZED RESPONSE", "structure-predictable physical priors", 716, 22, P.blue);
  panelLabel(b, "c", "DEPLOYMENT", "new molecules", 1364, 22, P.teal);

  sourceCaption(b, "Continuum response", "COSMOtherm · SMD(water)", 38, 125, 290);
  importAsset(b, "cavity", 56, 210, 250, 188, "Large continuum cavity");
  sourceCaption(b, "Explicit-water response", "OpenFF · interaction coordinates", 360, 125, 290);
  importAsset(b, "waterShell", 382, 205, 244, 190, "Large Packmol water shell");
  importAsset(b, "coulomb", 383, 397, 86, 78, "Bioicons Coulomb interaction — CC0");
  importAsset(b, "vdw", 494, 407, 105, 70, "Bioicons van der Waals interaction — CC0");

  sourceCaption(b, "Conformational response", "ConfSolv H₂O summaries", 38, 510, 290);
  importAsset(b, "conformers", 50, 600, 288, 182, "Large RDKit conformers");
  sourceCaption(b, "Explored high-fidelity response", "PIMD2 dH/dλ · not retained", 360, 510, 290);
  importAsset(b, "lambda", 378, 600, 252, 180, "Actual lambda response — explored only");

  stageTag(b, "STAGE 1", 44, 840, P.blue, P.bluePale, 112);
  addText(b, "physical response → frozen structure surrogates", 172, 847, 20, P.blue, 600);
  addText(b, "Source calculations are paid for once.", 45, 906, 18, P.muted, 400);

  ellipse(b, 953, 122, 100, 100, P.bluePale, "15-coordinate core", P.blue, 3);
  addText(b, "15", 984, 145, 38, P.blue, 700);
  addText(b, "named scalars", 965, 190, 15, P.blue, 600);
  drawResponseAtlas(b, 724, 245, 588, true);
  drawEndpoint(b, 718, 690, 590, true);

  drawDeployment(b, 1360, 126, 420, true);
  rule(b, 1360, 1060, 400, P.magenta, 2, "PIMD8 comparator rule");
  addText(b, "PIMD8 ≈ 0.205 kcal mol⁻¹", 1435, 1070, 17, P.magenta, 700);
  addText(b, "reference only", 1505, 1096, 14, P.muted, 400);
  return b.id;
}

async function buildBalanced() {
  const b = await createBoardOnPage("Variant C — balanced", "FIG1_C_BALANCED_WINNER");
  rect(b, 0, 0, W, H, P.paper, "Paper background");
  rect(b, 1310, 0, 490, H, "#F4FAF8", "Deployment field");
  rule(b, 570, 50, 2, P.rule, 1000, "Panel divider AB");
  rule(b, 1285, 50, 2, P.rule, 1000, "Panel divider BC");
  panelLabel(b, "a", "SOLVATION RESPONSE", "training information · generated once", 28, 20, P.orange);
  panelLabel(b, "b", "REUSABLE RESPONSE LAYER", "15 interpretable scalar coordinates", 600, 20, P.blue);
  panelLabel(b, "c", "STRUCTURE-ONLY", "deployment · SMILES input", 1320, 20, P.teal);

  drawSourceQuartet(b, 40, 128, false);
  stageTag(b, "STAGE 1", 42, 766, P.blue, P.bluePale, 112);
  addText(b, "learn structure → response", 175, 773, 20, P.blue, 600);
  importAsset(b, "molecule", 58, 835, 120, 78, "Stage 1 RDKit molecule");
  arrow(b, 196, 873, 276, 873, P.blue, "Structure to response surrogates", 3);
  for (let i = 0; i < 6; i++) ellipse(b, 296 + (i % 3) * 38, 838 + Math.floor(i / 3) * 47, 27, 27, i < 2 ? P.blue : P.bluePale, `Frozen response surrogate ${i + 1}`, P.blue);
  addText(b, "six frozen response surrogates", 270, 927, 17, P.blue, 600);
  arrow(b, 420, 873, 535, 873, P.blue, "Surrogates to reusable response layer", 3);
  addText(b, "source calculations do not run again", 130, 966, 17, P.orange, 600);

  drawResponseConstellation(b, 602, 118, 650);
  drawEndpoint(b, 602, 700, 650, true);

  drawDeployment(b, 1325, 122, 445, true);
  rule(b, 1328, 1060, 437, P.magenta, 2, "PIMD8 comparator rule");
  addText(b, "ARROW/PIMD8 ≈ 0.205 kcal mol⁻¹", 1374, 1070, 17, P.magenta, 700);
  addText(b, "accuracy reference only · not a retained teacher", 1356, 1096, 14, P.muted, 400);
  return b.id;
}

const ids = {};
ids.minimal = await buildMinimal();
ids.molecular = await buildMolecular();
ids.balanced = await buildBalanced();
await penpot.openPage(penpot.currentFile.pages.find((p) => p.name === "Variant C — balanced"));
return {
  file: penpot.currentFile.name,
  pages: penpotUtils.getPages(),
  boards: ids,
  selected: ids.balanced,
};
