#!/usr/bin/env python3
"""Build the single canonical v3 metric source and LaTeX macros."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
ACTIVE = ROOT / "active_solvai_v3"
OUT = ACTIVE / "results"


def main() -> None:
    gate = json.loads((OUT / "gate1/gate1_canonical_metrics.json").read_text())
    power = json.loads(
        (OUT / "power_reliability/power_reliability_canonical.json").read_text()
    )
    inventory = json.loads(
        (ACTIVE / "data/manifests/trajectory_inventory_summary.json").read_text()
    )
    metrics = {row["model"]: row for row in gate["primary_metrics"]}
    comparisons = {row["comparison"]: row for row in gate["primary_comparisons"]}
    design = power["smallest_numerically_adequate_design"]
    if design is None:
        raise AssertionError("the frozen planning grid has no numerically adequate design")

    canonical = {
        "schema_version": 1,
        "decision": "quantitative_gate_failed_no_simulation",
        "new_simulation": {
            "molecules": 0,
            "trajectories": 0,
            "simulated_ps": 0.0,
            "gpu_hours": 0.0,
        },
        "inherited_inventory": inventory,
        "gate1": {
            "n_molecules": gate["n_molecules"],
            "n_windows": gate["n_windows"],
            "generic_mae": metrics["generic_observed"]["mae"],
            "solvai_mae": metrics["solvai_conditioned"]["mae"],
            "solvai_minus_generic": comparisons["solvai_minus_generic"],
            "aligned_minus_shuffled": comparisons["aligned_minus_mean_shuffled"],
            "generic_minus_lambda": comparisons["generic_minus_lambda"],
            "generic_gate_passed": gate["generic_gate_passed"],
            "solvai_gate_passed": gate["solvai_identifiability_gate_passed"],
        },
        "power_reliability": {
            "minimum_effects_kcal_mol": power["minimum_effects_kcal_mol"],
            "reference_threshold_kcal_mol": power["reference_threshold_kcal_mol"],
            "smallest_predeclared_adequate_design": design,
            "launch_authorized": power["launch_authorized"],
        },
        "supported_claim": (
            "Generic early-run diagnostics contain modest development signal, but frozen "
            "SolvAI response coordinates do not improve held-out sampling-difficulty "
            "prediction; no v3 policy or prospective simulation is authorized."
        ),
    }
    json_path = OUT / "canonical_metrics.json"
    json_path.write_text(json.dumps(canonical, indent=2) + "\n")

    rows = [
        ("gate1_generic_mae", canonical["gate1"]["generic_mae"]),
        ("gate1_solvai_mae", canonical["gate1"]["solvai_mae"]),
        (
            "gate1_solvai_minus_generic",
            comparisons["solvai_minus_generic"]["mean_difference"],
        ),
        ("gate1_solvai_ci90_low", comparisons["solvai_minus_generic"]["ci90_low"]),
        ("gate1_solvai_ci90_high", comparisons["solvai_minus_generic"]["ci90_high"]),
        (
            "gate1_aligned_minus_shuffled",
            comparisons["aligned_minus_mean_shuffled"]["mean_difference"],
        ),
        ("minimum_design_molecules", design["n_molecules"]),
        (
            "minimum_design_ps_per_stream_window",
            design["production_ps_per_stream_window"],
        ),
        ("minimum_design_total_ps", design["production_total_ps"]),
        ("minimum_design_power_budget5", design["power_budget5"]),
        ("minimum_design_power_budget7", design["power_budget7"]),
        (
            "minimum_design_reference_probability",
            design["reference_reliability_probability"],
        ),
        (
            "minimum_design_production_gpu_hours",
            design["projected_production_gpu_hours"],
        ),
        (
            "minimum_design_reserved_gpu_hours",
            design["operational_reservation_gpu_hours"],
        ),
        ("new_simulation_gpu_hours", 0.0),
    ]
    pd.DataFrame(rows, columns=["metric", "value"]).to_csv(
        OUT / "canonical_metrics.csv", index=False
    )

    macros = f"""% Generated by active_solvai_v3/scripts/finalize_v3.py
\\newcommand{{\\GateGenericMAE}}{{{metrics['generic_observed']['mae']:.3f}}}
\\newcommand{{\\GateSolvAIMAE}}{{{metrics['solvai_conditioned']['mae']:.3f}}}
\\newcommand{{\\GateSolvAIDifference}}{{{comparisons['solvai_minus_generic']['mean_difference']:.4f}}}
\\newcommand{{\\GateSolvAILow}}{{{comparisons['solvai_minus_generic']['ci90_low']:.4f}}}
\\newcommand{{\\GateSolvAIHigh}}{{{comparisons['solvai_minus_generic']['ci90_high']:.4f}}}
\\newcommand{{\\MinimumDesignMolecules}}{{{int(design['n_molecules'])}}}
\\newcommand{{\\MinimumDesignDuration}}{{{int(design['production_ps_per_stream_window']):,}}}
\\newcommand{{\\MinimumDesignTotalPs}}{{{int(design['production_total_ps']):,}}}
\\newcommand{{\\MinimumDesignPowerFive}}{{{design['power_budget5']:.3f}}}
\\newcommand{{\\MinimumDesignPowerSeven}}{{{design['power_budget7']:.3f}}}
\\newcommand{{\\MinimumDesignReliability}}{{{design['reference_reliability_probability']:.3f}}}
\\newcommand{{\\MinimumDesignProductionGPU}}{{{design['projected_production_gpu_hours']:,.0f}}}
\\newcommand{{\\MinimumDesignReservedGPU}}{{{design['operational_reservation_gpu_hours']:,.0f}}}
"""
    (ACTIVE / "paper/generated_metrics.tex").write_text(macros)
    print(json.dumps(canonical, indent=2))


if __name__ == "__main__":
    main()
