"""Build vector mathematical labels used in the Penpot Figure 1 source."""

from pathlib import Path

import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent


def main() -> None:
    # Keep math glyphs as text spans: Penpot imports this form reliably while
    # retaining the typographic subscript generated by Matplotlib mathtext.
    plt.rcParams["svg.fonttype"] = "none"
    fig = plt.figure(figsize=(2.0, 0.75), facecolor="none")
    fig.text(
        0.5,
        0.5,
        r"$\Delta G_{\mathrm{hyd}}$",
        color="#0B8978",
        fontsize=34,
        ha="center",
        va="center",
    )
    fig.savefig(
        HERE / "delta_g_hyd_mathtext.svg",
        format="svg",
        transparent=True,
        bbox_inches="tight",
        pad_inches=0.01,
    )
    plt.close(fig)


if __name__ == "__main__":
    main()
