"""Curated structure identities for the 2022 ARROW neutral benchmark.

The paper workbook contains names and numerical values but no connection tables.
These SMILES encode the neutral species named by the workbook.  They are checked
against FreeSolv where an exact structure is present and canonicalized by RDKit
before use.
"""

BENCHMARK_SMILES = {
    "Cyclopropane": "C1CC1",
    "Cyclopentane": "C1CCCC1",
    "Cyclohexane": "C1CCCCC1",
    "Cycloheptane": "C1CCCCCC1",
    "Isobutane": "CC(C)C",
    "NeoPentane": "CC(C)(C)C",
    "Methane": "C",
    "Ethane": "CC",
    "Propane": "CCC",
    "Butane": "CCCC",
    "Pentane": "CCCCC",
    "Hexane": "CCCCCC",
    "Octane": "CCCCCCCC",
    "Ethene": "C=C",
    "Propene": "CC=C",
    "Buta-13-diene": "C=CC=C",
    "But-1-ene": "C=CCC",
    "pent-1-ene": "C=CCCC",
    "methylamine": "CN",
    "dimethylamine": "CNC",
    "trimethylamine": "CN(C)C",
    "butanamine": "CCCCN",
    "ethylamine": "CCN",
    "DiMethylEther": "COC",
    "DiethylEther": "CCOCC",
    "DiMethoxyEthane": "COCCOC",
    "MethylPropylEther": "CCCOC",
    "acetaldehyde": "CC=O",
    "propionaldehyde": "CCC=O",
    "buytyraldehyde": "CCCC=O",
    "Acetone": "CC(=O)C",
    "2-Butanone": "CCC(=O)C",
    "2-Pentanone": "CCCC(=O)C",
    "3-Pentanone": "CCC(=O)CC",
    "hexa2none": "CCCCC(=O)C",
    "AceticAcid": "CC(=O)O",
    "propionicacid": "CCC(=O)O",
    "butyricacid": "CCCC(=O)O",
    "Benzene": "c1ccccc1",
    "Napthalene": "c1ccc2ccccc2c1",
    "Anthracene": "c1ccc2cc3ccccc3cc2c1",
    "tetracene": "c1ccc2cc3cc4ccccc4cc3cc2c1",
    "pyrene": "c1cc2ccc3cccc4ccc(c1)c2c34",
    "phenanthrene": "c1ccc2c(c1)ccc1ccccc12",
    "Biphenyl": "c1ccc(-c2ccccc2)cc1",
    "Toluene": "Cc1ccccc1",
    "Phenol": "Oc1ccccc1",
    "p-cresol": "Cc1ccc(O)cc1",
    "m-cresol": "Cc1cccc(O)c1",
    "o-cresol": "Cc1ccccc1O",
    "Water": "O",
    "Methanol": "CO",
    "Ethanol": "CCO",
    "Propanol": "CCCO",
    "2-Propanol": "CC(O)C",
    "1-Butanol": "CCCCO",
    "2-Butanol": "CCC(O)C",
    "2-Methyl-2-Propanol": "CC(C)(C)O",
    "1-Pentanol": "CCCCCO",
    "2-Methyl-2-Butanol": "CCC(C)(C)O",
    "2-Pentanol": "CCCC(O)C",
    "3-Pentanol": "CCC(O)CC",
    "Cyclohexanol": "OC1CCCCC1",
    "Octanol": "CCCCCCCCO",
    "EthylAcetate": "CCOC(=O)C",
    "MethylPropionate": "CCC(=O)OC",
    "PropylAcetate": "CCCOC(=O)C",
    "ButylAcetate": "CCCCOC(=O)C",
    "Acetamide": "CC(=O)N",
    "N-Methylacetamide": "CC(=O)NC",
    "DiMethylAcetamide": "CC(=O)N(C)C",
    "propionamide": "CCC(=O)N",
    "MethaneThiol": "CS",
    "EthaneThiol": "CCS",
    "Propanethiol": "CCCS",
    "1-Butanethiol": "CCCCS",
    "DiMethylSulfide": "CSC",
    "DiEthylSulfide": "CCSCC",
    "EthylMethylSulfide": "CCSC",
    "DimethylDisulfide": "CSSC",
    "3-methyl-indole": "Cc1c[nH]c2ccccc12",
    "Aniline": "Nc1ccccc1",
    "Imidazole": "c1ncc[nH]1",
    "Pyrrole": "c1cc[nH]c1",
    "pyridine": "n1ccccc1",
}

# Prefer a compact, solute-only, force-field-typed structure where one is in the
# supplied snapshot.  Missing entries remain missing rather than being inferred.
HIN_BY_NAME = {
    "Cyclopropane": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C03H06_Cyclopropane.hin",
    "Cyclopentane": "repositories/Simulations/HIN/ALKANES/C05H10_Cyclopentane.hin",
    "Cyclohexane": "repositories/Simulations/HIN/ALKANES/C06H12_Cyclohexane.hin",
    "Cycloheptane": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C07H14_Cycloheptane.hin",
    "NeoPentane": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H12_NeoPentane.hin",
    "Isobutane": "repositories/Simulations/HIN/ALKANES/C04H10_Isobutane.hin",
    "Methane": "repositories/Simulations/HIN/ALKANES/Methane.hin",
    "Ethane": "repositories/Simulations/HIN/ALKANES/Ethane.hin",
    "Propane": "repositories/Simulations/HIN/ALKANES/C03H08_Propane.hin",
    "Butane": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/TI/butane_512_example/Input/HIN/Butane.hin",
    "Pentane": "repositories/Simulations/HIN/ALKANES/C05H12_Pentane.hin",
    "Hexane": "repositories/Simulations/HIN/ALKANES/C06H14_Hexane.hin",
    "Octane": "repositories/Simulations/HIN/ALKANES/C08H18_Octane.hin",
    "Ethene": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C02H04_Ethene.hin",
    "Propene": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C03H06_Propene.hin",
    "Buta-13-diene": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H06_Butadiene.hin",
    "But-1-ene": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H08_1-Butene_1.hin",
    "pent-1-ene": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H10_1-Pentene.hin",
    "methylamine": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C01H05N1_Methylamine.hin",
    "dimethylamine": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C02H07N1_DiMethylAmine.hin",
    "trimethylamine": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C03H09N1_Trimethylamine.hin",
    "butanamine": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H11N1_1-Butanamine.hin",
    "ethylamine": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C02H07N1_Ethylamine.hin",
    "DiMethylEther": "repositories/Simulations/HIN/C02H06O1_DiMethylEther.hin",
    "DiethylEther": "repositories/Simulations/MD_TOOLS_PY/test/test_dimers/data/input/DIMERS_ARROW2/C04H12O2_DiEthylEther-Water.d39.c0197.hin",
    "DiMethoxyEthane": (
        "repositories_recovered/FF-Tools/ExtractionFromMDExample/"
        "Functional_Groups_Molecules_HINS_TYPIFIED/055_Ethers/"
        "C04H10O2_DiMethoxyEthane.hin"
    ),
    "acetaldehyde": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C02H04O1_Acetaldehyde.hin",
    "propionaldehyde": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C03H06O1_Propionaldehyde.hin",
    "buytyraldehyde": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H08O1_Butanal.hin",
    "Acetone": "repositories/Simulations/HIN/Acetone.hin",
    "2-Butanone": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H08O1_2-Butanone.hin",
    "2-Pentanone": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H10O1_2-Pentanone.hin",
    "3-Pentanone": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H10O1_3-Pentanone.hin",
    "hexa2none": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/hexa2none.hin",
    "AceticAcid": "repositories/Simulations/HIN/C02H04O2_AceticAcid.hin",
    "propionicacid": "repositories/Simulations/HIN/propionicacid.hin",
    "butyricacid": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/butyricacid.hin",
    "Benzene": "repositories/Simulations/HIN/C06H06_Benzene.hin",
    "Napthalene": "repositories/Simulations/HIN/C10H08_Naphthalene.hin",
    "Anthracene": "repositories/Simulations/HIN/C14H10_Anthracene.hin",
    "tetracene": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C18H12_Tetracene.hin",
    "phenanthrene": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C14H10_Phenanthrene.hin",
    "Biphenyl": "repositories/Simulations/HIN/C12H10_Biphenyl.hin",
    "Toluene": "repositories/Simulations/HIN/C07H08_Toluene.hin",
    "Phenol": "repositories/Simulations/HIN/C06H06O1_Phenol_General.hin",
    "p-cresol": "repositories/Simulations/HIN/C07H08O1_Cresol-para-CA.hin",
    "m-cresol": "repositories/Simulations/HIN/C07H08O1_Cresol-meta.hin",
    "o-cresol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C07H08O1_Cresol-ortho.hin",
    "Water": "repositories/Simulations/HIN/H2O_Water.hin",
    "Methanol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C01H04O1_Methanol.hin",
    "Ethanol": "repositories/Simulations/HIN/C02H06O1_Ethanol.hin",
    "Propanol": "repositories/Simulations/HIN/C03H08O1_1-Propanol.hin",
    "1-Butanol": "repositories/Simulations/HIN/C04H10O1_1-Butanol.hin",
    "1-Pentanol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H12O1_1-Pentanol.hin",
    "2-Methyl-2-Butanol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H12O1_2-Methyl-2-Butanol.hin",
    "2-Pentanol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H12O1_2-Pentanol.hin",
    "3-Pentanol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H12O1_3-Pentanol.hin",
    "Octanol": "repositories/Simulations/HIN/C08H18O1_Octanol.hin",
    "EthylAcetate": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H08O2_EthylAcetate.hin",
    "MethylPropionate": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H08O2_MethylPropionate.hin",
    "PropylAcetate": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C05H10O2_PropylAcetate.hin",
    "ButylAcetate": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C06H12O2_ButylAcetate.hin",
    "Acetamide": "repositories/Simulations/HIN/Acetamide.hin",
    "N-Methylacetamide": "repositories/Simulations/HIN/C03H07N1O1_N-Methylacetamide_01.hin",
    "DiMethylAcetamide": "repositories/Simulations/HIN/C04H09N1O1_DiMethylAcetamide.hin",
    "3-methyl-indole": "repositories/Simulations/HIN/C09H09N1_3-methyl-indole.hin",
    "Aniline": "repositories/Simulations/HIN/C06H07N1_Aniline.hin",
    "Imidazole": "repositories/Simulations/HIN/C03H04N2_Imidazole.hin",
    "Pyrrole": "repositories/Simulations/HIN/Pyrrole.hin",
    "pyridine": "repositories/Simulations/HIN/Pyridine.hin",
    "MethaneThiol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C01H04S1_Methanethiol.hin",
    "EthaneThiol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C02H06S1_EthaneThiol.hin",
    "1-Butanethiol": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H10S1_1-Butanethiol.hin",
    "DiMethylSulfide": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C02H06S1_DiMethylSulfide.hin",
    "DiEthylSulfide": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C04H10S1_DiethylSulfide.hin",
    "EthylMethylSulfide": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C03H08S1_EthylMethylSulfide.hin",
    "DimethylDisulfide": "repositories/arbalest/OPENMM_ARROW/plugins/arrow/tests/HIN/C02H06S2_DimethylDisulfide.hin",
}
